const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const { parseHlsManifest } = require('@m3u8/contracts');
const { httpUrl } = require('../utils/urls');
const { scopeMediaHeaders, startScopedMediaProxy: defaultStartProxy } = require('@m3u8/downloader-engine/src/core/MediaRequest');

// Short "hover to hear" samples of an audio track, generated by the bundled
// FFmpeg into a private temp directory. Only one sample is produced at a time.
const SAMPLE_SECONDS = 10;
const START_FRACTION = 0.25;
const DIRECTORY_PREFIX = 'snagthis-audio-samples-';
const LOW_RISK_HEADERS = ['referer', 'origin', 'user-agent'];

function sampleError(message, code) {
  const error = new Error(message);
  error.code = code;
  return error;
}


function processAlive(pid) {
  try { process.kill(pid, 0); return true; } catch (error) { return error.code === 'EPERM'; }
}

// Samples from a crashed earlier run are removed; a live process keeps its own.
function removeStaleDirectories(root) {
  let entries = [];
  try { entries = fs.readdirSync(root, { withFileTypes: true }); } catch { return; }
  for (const entry of entries) {
    const match = entry.isDirectory() && entry.name.startsWith(DIRECTORY_PREFIX) && entry.name.slice(DIRECTORY_PREFIX.length).match(/^(\d+)-/);
    if (!match || (Number(match[1]) !== process.pid && processAlive(Number(match[1])))) continue;
    try { fs.rmSync(path.join(root, entry.name), { recursive: true, force: true }); } catch { /* Best effort. */ }
  }
}

function createAudioSampler({ ffmpegPath, logger, tempRoot = os.tmpdir(), timeoutMs = 25_000, maxFiles = 24, startScopedMediaProxy = defaultStartProxy } = {}) {
  removeStaleDirectories(tempRoot);
  const directory = path.join(tempRoot, `${DIRECTORY_PREFIX}${process.pid}-${crypto.randomBytes(4).toString('hex')}`);
  const cache = new Map();
  let current = null;
  let closed = false;

  function evict() {
    while (cache.size > maxFiles) {
      const [key, filePath] = cache.entries().next().value;
      cache.delete(key);
      fs.promises.rm(filePath, { force: true }).catch(() => {});
    }
  }

  function runFfmpeg(args, signal) {
    return new Promise((resolve, reject) => {
      const child = spawn(ffmpegPath, args, { stdio: ['ignore', 'ignore', 'ignore'], windowsHide: true });
      const kill = () => { try { child.kill('SIGKILL'); } catch { /* Already exited. */ } };
      signal.addEventListener('abort', kill, { once: true });
      child.once('error', () => {});
      child.once('close', (code) => {
        signal.removeEventListener('abort', kill);
        if (signal.aborted) reject(signal.reason);
        else if (code === 0) resolve();
        else reject(sampleError('FFmpeg could not produce an audio sample', 'SAMPLE_FAILED'));
      });
    });
  }

  async function playlistDuration(proxyUrl, renditionUrl, signal) {
    try {
      const response = await fetch(proxyUrl, { signal });
      if (!response.ok) { await response.body?.cancel(); return null; }
      const text = await response.text();
      const manifest = parseHlsManifest(text, renditionUrl);
      const duration = Number(manifest.durationSeconds);
      return Number.isFinite(duration) && duration > 0 ? duration : null;
    } catch (error) {
      if (signal.aborted) throw signal.reason;
      return null;
    }
  }

  async function generate({ mediaUrl, renditionUrl, streamIndex, durationSeconds, headers = {} } = {}, signal) {
    if (closed) throw sampleError('Audio samples are unavailable', 'SAMPLE_UNAVAILABLE');
    if (!ffmpegPath) throw sampleError('FFmpeg is unavailable', 'SAMPLE_UNAVAILABLE');
    const media = httpUrl(mediaUrl);
    const rendition = renditionUrl === undefined || renditionUrl === null || renditionUrl === '' ? null : httpUrl(renditionUrl);
    const index = streamIndex === undefined || streamIndex === null ? 0 : streamIndex;
    if (!media || (renditionUrl && !rendition) || !Number.isInteger(index) || index < 0 || index > 63) {
      throw sampleError('Invalid audio sample request', 'INVALID_SAMPLE_REQUEST');
    }
    const knownDuration = Number.isFinite(durationSeconds) && durationSeconds > 0 ? durationSeconds : null;

    // A newer hover replaces the previous one; FFmpeg is killed immediately.
    if (current) current.abort(sampleError('Superseded by a newer audio sample', 'SAMPLE_SUPERSEDED'));
    const controller = new AbortController();
    current = controller;
    const onOuterAbort = () => controller.abort(sampleError('The audio sample request was cancelled', 'SAMPLE_ABORTED'));
    if (signal) {
      if (signal.aborted) onOuterAbort();
      else signal.addEventListener('abort', onOuterAbort, { once: true });
    }
    const timer = setTimeout(() => controller.abort(sampleError('The audio sample took too long', 'SAMPLE_TIMEOUT')), timeoutMs);
    const key = crypto.createHash('sha256')
      .update(JSON.stringify([rendition ? rendition.href : media.href, rendition ? null : index, knownDuration]))
      .digest('hex');
    const filePath = path.join(directory, `${key}.m4a`);
    const partPath = `${filePath}.${crypto.randomBytes(4).toString('hex')}.part`;
    let proxy = null;
    try {
      const cached = cache.get(key);
      if (cached) {
        try {
          await fs.promises.access(cached);
          cache.delete(key);
          cache.set(key, cached);
          return cached;
        } catch { cache.delete(key); }
      }
      await fs.promises.mkdir(directory, { recursive: true, mode: 0o700 });
      const { signal: work } = controller;
      let inputArgs;
      let mapArgs;
      let start = 0;
      if (rendition) {
        // Credentials stay with the inspected media origin; the proxy decides
        // per request which saved headers may reach each playlist or segment.
        proxy = await startScopedMediaProxy({ rootUrl: rendition.href, headers, credentialOrigin: media.href });
        if (work.aborted) throw work.reason;
        const duration = await playlistDuration(proxy.url, rendition.href, work) || knownDuration;
        if (duration) start = duration * START_FRACTION;
        inputArgs = ['-protocol_whitelist', 'http,tcp,crypto', '-f', 'hls', '-allowed_extensions', 'ALL',
          '-allowed_segment_extensions', 'ALL', '-extension_picky', '0', '-ss', start.toFixed(3), '-i', proxy.url];
        mapArgs = ['-map', '0:a:0'];
      } else {
        // FFmpeg sends -headers to every host it reaches, so only headers that
        // may cross origins are forwarded on this path.
        const scoped = scopeMediaHeaders(headers, media.href, { credentialOrigin: media.href });
        const lines = LOW_RISK_HEADERS.filter((name) => scoped[name]).map((name) => `${name}: ${scoped[name]}\r\n`).join('');
        if (knownDuration) start = knownDuration * START_FRACTION;
        inputArgs = ['-protocol_whitelist', 'http,https,tcp,tls,crypto', ...(lines ? ['-headers', lines] : []),
          '-ss', start.toFixed(3), '-i', media.href];
        mapArgs = ['-map', `0:a:${index}`];
      }
      await runFfmpeg(['-hide_banner', '-loglevel', 'error', '-nostdin', '-y', ...inputArgs,
        '-t', String(SAMPLE_SECONDS), '-vn', ...mapArgs, '-c:a', 'aac', '-b:a', '96k', '-ac', '2',
        '-movflags', '+faststart', '-f', 'mp4', partPath], work);
      const stat = await fs.promises.stat(partPath);
      if (!stat.size) throw sampleError('FFmpeg produced an empty audio sample', 'SAMPLE_FAILED');
      await fs.promises.rename(partPath, filePath);
      cache.set(key, filePath);
      evict();
      return filePath;
    } catch (error) {
      if (proxy && proxy.lastError && error.code === 'SAMPLE_FAILED') error.code = 'SAMPLE_SOURCE_FAILED';
      if (logger && !['SAMPLE_ABORTED', 'SAMPLE_SUPERSEDED'].includes(error.code)) {
        logger.warn('Audio sample failed', { kind: rendition ? 'hls' : 'stream', code: error.code || 'SAMPLE_FAILED' });
      }
      throw error;
    } finally {
      clearTimeout(timer);
      if (signal) signal.removeEventListener('abort', onOuterAbort);
      if (current === controller) current = null;
      if (!controller.signal.aborted) controller.abort();
      if (proxy) await proxy.close().catch(() => {});
      await fs.promises.rm(partPath, { force: true }).catch(() => {});
    }
  }

  function close() {
    closed = true;
    if (current) current.abort(sampleError('The audio sampler is closing', 'SAMPLE_ABORTED'));
    current = null;
    cache.clear();
    try { fs.rmSync(directory, { recursive: true, force: true }); } catch { /* Best effort. */ }
  }

  return { generate, close, directory };
}

module.exports = { createAudioSampler };
