const { test, expect, chromium } = require('@playwright/test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { root, startRenderer, launchDesktop } = require('./helpers');

test('first connection: one-click approve (deny, allow), code fallback, disconnect and re-pair', async () => {
  test.setTimeout(180_000);
  const renderer = await startRenderer();
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'snagthis-pairing-browser-'));
  const evidence = path.join(root, 'work/verification/pairing-onboarding');
  fs.mkdirSync(evidence, { recursive: true });
  let native;
  let context;
  let desktop;
  let clockShifted = false;
  const cleanupStage = stage => fs.writeFileSync(path.join(evidence, 'cleanup.json'), JSON.stringify({ stage, at: new Date().toISOString() }));
  try {
    native = await launchDesktop(renderer.baseUrl);
    desktop = await native.app.firstWindow();
    await desktop.waitForFunction(() => typeof window.desktop?.getAppInfo === 'function');
    await expect.poll(() => desktop.evaluate(async () => (await window.desktop.getAppInfo()).apiStartupState)).toBe('ready');
    await expect(desktop.getByRole('button', { name: 'Add SnagThis to Chrome', exact: true })).toBeVisible();
    await desktop.screenshot({ path: path.join(evidence, 'desktop-first-launch.png'), animations: 'disabled' });
    await desktop.getByRole('button', { name: 'Already installed? Connect Chrome', exact: true }).click();
    const setup = desktop.getByRole('region', { name: 'Chrome extension setup' });
    await expect(setup).toContainText('Extensions (the puzzle icon), then SnagThis, then Connect');
    await expect(setup).toContainText('four digits');
    // The code stays an explicit fallback: nothing is generated by opening Settings.
    await expect(setup.getByRole('button', { name: 'Show connection code', exact: true })).toBeVisible();
    await expect(desktop.getByLabel('Connection code', { exact: true })).toHaveCount(0);
    await desktop.screenshot({ path: path.join(evidence, 'desktop-setup.png'), animations: 'disabled' });

    const extension = path.join(root, 'apps/extension');
    context = await chromium.launchPersistentContext(profile, {
      channel: 'chromium', headless: true, viewport: { width: 480, height: 560 },
      args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
    });
    const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
    const extensionId = new URL(worker.url()).host;
    const popupUrl = `chrome-extension://${extensionId}/popup.html?apiBase=${encodeURIComponent(native.baseUrl)}`;
    let popup = await context.newPage();
    // Simulate a closed app as a network failure, without faking an API response
    // or modifying any authentication checks.
    await popup.route(`${native.baseUrl}/**`, route => route.abort('connectionrefused'));
    await popup.goto(popupUrl);
    await expect(popup.locator('#connection-banner')).toContainText('Save supported files in Chrome. Open SnagThis for streams and more.');
    await expect(popup.locator('#connection-banner').getByRole('button', { name: 'Open SnagThis', exact: true })).toBeVisible();
    await popup.screenshot({ path: path.join(evidence, 'extension-offline.png'), animations: 'disabled' });
    await popup.unroute(`${native.baseUrl}/**`);
    await expect(popup.locator('#connection-banner').getByRole('button', { name: 'Connect', exact: true })).toBeVisible();
    expect((await fetch(`${native.baseUrl}/v1/queue`)).status).toBe(401);

    // snagthis://open/pair as Chrome delivers it to the running app; the link carries no ID or secret.
    const openPairLink = () => native.app.evaluate(({ app }) => { app.emit('open-url', { preventDefault() {} }, 'snagthis://open/pair'); });
    const badge = () => worker.evaluate(() => chrome.action.getBadgeText({}));
    // Record Allow's state the moment the dialog first renders it.
    const watchAllow = () => desktop.evaluate(() => {
      window.__allowSeen = null;
      const observer = new MutationObserver(() => {
        const allow = [...document.querySelectorAll('.pairing-dialog button')].find(button => button.textContent === 'Allow');
        if (allow && !window.__allowSeen) { window.__allowSeen = { disabled: allow.disabled, focused: document.activeElement === allow, arming: allow.classList.contains('arming') }; observer.disconnect(); }
      });
      observer.observe(document.body, { childList: true, subtree: true });
    });
    const approveDialog = desktop.getByRole('dialog', { name: 'Connect Chrome?' });

    // 1. One click, then Deny in SnagThis.
    await popup.locator('#connection-banner').getByRole('button', { name: 'Connect', exact: true }).click();
    const popupDigits = popup.locator('#sheet .pair-digits');
    await expect(popupDigits).toBeVisible();
    const deniedCode = await popupDigits.getAttribute('data-code');
    expect(deniedCode).toMatch(/^\d{4}$/);
    // Cartridge: one instruction around the digits, a pip countdown, and the code link in the footer.
    await expect(popup.locator('#sheet')).toContainText('Match in SnagThis');
    await expect(popup.locator('#sheet')).toContainText('Then choose Allow there.');
    await expect(popup.locator('#sheet .pair-status')).toContainText(/(Opening SnagThis…|Waiting for Allow)·\d:\d\d/);
    await expect(popup.locator('#sheet .pair-pip')).toHaveCount(12);
    await expect(popup.locator('#sheet .pair-tick')).toHaveAttribute('aria-hidden', 'true');
    await expect(popup.locator('#sheet .pair-foot')).toContainText('SnagThis didn’t open?');
    await expect(popup.getByRole('button', { name: 'Use a code', exact: true })).toBeVisible();
    await expect(popup.getByRole('button', { name: 'Show SnagThis', exact: true })).toBeVisible();
    await expect(popup.locator('#sheet .pair-devchip')).toHaveText('DEV BUILD');
    await expect.poll(badge).toBe(deniedCode);
    await expect(setup).toContainText('Chrome is asking to connect');
    await popup.screenshot({ path: path.join(evidence, 'extension-one-click-waiting.png'), animations: 'disabled' });
    await desktop.screenshot({ path: path.join(evidence, 'desktop-review.png'), animations: 'disabled' });
    await watchAllow();
    await openPairLink();
    await expect(approveDialog).toBeVisible();
    await expect(approveDialog.getByRole('img', { name: /^Match code/ })).toHaveAttribute('data-code', deniedCode);
    await expect(approveDialog).toContainText(extensionId);
    await expect(approveDialog.locator('.pairing-who')).toContainText(`${extensionId.slice(0, 6)}…${extensionId.slice(-6)}`);
    await expect(approveDialog).toContainText('Not Web Store');
    await expect.poll(() => desktop.evaluate(() => window.__allowSeen)).toEqual({ disabled: true, focused: false, arming: true });
    // The Settings row repeats the code, so it hides while the dialog is open.
    await expect(setup.getByText('Chrome is asking to connect')).toBeHidden();
    await desktop.screenshot({ path: path.join(evidence, 'desktop-approve-dialog.png'), animations: 'disabled' });
    await approveDialog.getByRole('button', { name: 'Deny', exact: true }).click();
    await expect(approveDialog).toBeHidden();
    await expect(desktop.getByText('Chrome wasn’t connected. It can ask again in an hour.')).toBeVisible();
    await desktop.screenshot({ path: path.join(evidence, 'desktop-denied-toast.png'), animations: 'disabled' });
    await expect(popup.locator('#sheet')).toContainText('Not connected');
    await expect(popup.locator('#sheet')).toContainText('SnagThis chose Deny. Chrome can ask again in an hour.');
    await expect.poll(badge).toBe('');
    expect(await worker.evaluate(async () => (await chrome.storage.local.get('appToken')).appToken)).toBeUndefined();
    expect((await fetch(`${native.baseUrl}/v1/queue`)).status).toBe(401);
    await popup.screenshot({ path: path.join(evidence, 'extension-one-click-denied.png'), animations: 'disabled' });

    // 2. The fallback: a six-digit code shown only after an explicit click in SnagThis.
    await popup.getByRole('button', { name: 'Use a code', exact: true }).click();
    await expect(popup.locator('#sheet')).toContainText('Settings → Chrome extension → Show connection code');
    await expect(popup.getByRole('button', { name: 'Open app settings', exact: true })).toBeVisible();
    await expect(popup.getByLabel('Connection code', { exact: true })).toBeFocused();
    await popup.screenshot({ path: path.join(evidence, 'extension-connect-code.png'), animations: 'disabled' });

    await setup.getByRole('button', { name: 'Show connection code', exact: true }).click();
    const originalCode = (await desktop.getByLabel('Connection code', { exact: true }).textContent()).trim();
    expect(originalCode).toMatch(/^\d{6}$/);
    await expect(setup).toContainText('Expires in');
    // Exercise Copy without overwriting the owner's system clipboard.
    await desktop.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: {
      writeText: async value => { window.__copiedPairingCode = value; },
    } }));
    await setup.getByRole('button', { name: 'Copy code', exact: true }).click();
    await expect(setup.getByRole('button', { name: 'Copied', exact: true })).toBeVisible();
    expect(await desktop.evaluate(() => window.__copiedPairingCode)).toBe(originalCode);
    await desktop.screenshot({ path: path.join(evidence, 'desktop-code.png'), animations: 'disabled' });

    // Six digits submit on their own; no Connect click is needed.
    await popup.getByLabel('Connection code', { exact: true }).fill(originalCode === '000000' ? '111111' : '000000');
    await expect(popup.locator('.sheet-error')).toContainText('incorrect or expired');
    // Advance only these isolated desktop clocks. The real API expiry check
    // still rejects the code through its unchanged five-minute boundary.
    clockShifted = true;
    await native.app.evaluate(() => { globalThis.__pairingRealNow = Date.now; Date.now = () => globalThis.__pairingRealNow() + 301000; });
    await desktop.evaluate(() => { window.__pairingRealNow = Date.now; Date.now = () => window.__pairingRealNow() + 301000; });
    await expect(setup.getByRole('button', { name: 'Get a new code', exact: true })).toBeVisible();
    await expect(desktop.getByLabel('Connection code', { exact: true })).toHaveCount(0);
    const expiredResponse = popup.waitForResponse(response => response.url().endsWith('/v1/pair/complete'));
    await popup.getByLabel('Connection code', { exact: true }).fill(originalCode);
    expect((await expiredResponse).status()).toBe(403);
    await expect(popup.locator('.sheet-error')).toContainText('Settings → Chrome extension');
    await popup.screenshot({ path: path.join(evidence, 'extension-expired-code.png'), animations: 'disabled' });
    await desktop.screenshot({ path: path.join(evidence, 'desktop-expired-code.png'), animations: 'disabled' });

    await setup.getByRole('button', { name: 'Get a new code', exact: true }).click();
    const freshCode = (await desktop.getByLabel('Connection code', { exact: true }).textContent()).trim();
    await popup.getByLabel('Connection code', { exact: true }).fill(freshCode);
    await expect(popup.locator('#sheet')).not.toBeVisible();
    await expect(popup.locator('#connection-banner')).toBeHidden();
    await expect(popup.locator('#notice')).toContainText('Connected to SnagThis');
    await expect(setup).toContainText('Connected to Chrome extension');
    await expect(setup.getByRole('list', { name: 'Connected browsers' }).getByRole('listitem')).toHaveCount(1);
    await expect(desktop.getByLabel('Connection code', { exact: true })).toHaveCount(0);
    await popup.screenshot({ path: path.join(evidence, 'extension-connected-code.png'), animations: 'disabled' });
    await desktop.screenshot({ path: path.join(evidence, 'desktop-connected.png'), animations: 'disabled' });
    await native.app.evaluate(() => { Date.now = globalThis.__pairingRealNow; delete globalThis.__pairingRealNow; });
    await desktop.evaluate(() => { Date.now = window.__pairingRealNow; delete window.__pairingRealNow; });
    clockShifted = false;
    const codeToken = await worker.evaluate(async () => (await chrome.storage.local.get('appToken')).appToken);
    const desktopToken = await desktop.evaluate(async () => (await window.desktop.getAppInfo()).apiAuthToken);
    expect(codeToken).toMatch(/^[0-9a-f]{64}$/);
    expect(codeToken).not.toBe(desktopToken);

    // 3. Disconnect this browser from the popup; its key stops working at once.
    await popup.locator('#settings-button').click();
    await popup.locator('#sheet').getByRole('tab', { name: 'Connection, Connected', exact: true }).click();
    await expect(popup.locator('#sheet')).toContainText('Connected to SnagThis');
    await popup.screenshot({ path: path.join(evidence, 'extension-settings-connected.png'), animations: 'disabled' });
    await popup.locator('#sheet').getByRole('button', { name: 'Disconnect', exact: true }).click();
    await expect(popup.locator('#connection-banner')).toContainText('Disconnected from SnagThis. Supported files still save in Chrome.');
    expect((await fetch(`${native.baseUrl}/v1/queue`, { headers: { Authorization: `Bearer ${codeToken}` } })).status).toBe(401);
    await expect(setup.getByRole('list', { name: 'Connected browsers' })).toHaveCount(0);
    await popup.screenshot({ path: path.join(evidence, 'extension-disconnected.png'), animations: 'disabled' });

    // 4. Re-pair with one click. Chrome closes the popup when SnagThis takes focus.
    await popup.locator('#connection-banner').getByRole('button', { name: 'Connect again', exact: true }).click();
    await expect(popupDigits).toBeVisible();
    const allowedCode = await popupDigits.getAttribute('data-code');
    expect(allowedCode).toMatch(/^\d{4}$/);
    await popup.close();
    await watchAllow();
    await openPairLink();
    await expect(approveDialog).toBeVisible();
    await expect(approveDialog.getByRole('img', { name: /^Match code/ })).toHaveAttribute('data-code', allowedCode);
    await expect(approveDialog).toContainText('Not Web Store');
    await expect.poll(() => desktop.evaluate(() => window.__allowSeen)).toEqual({ disabled: true, focused: false, arming: true });
    await approveDialog.getByRole('button', { name: 'Allow', exact: true }).click();
    const connectedDialog = desktop.getByRole('dialog', { name: 'Chrome connected' });
    await expect(connectedDialog).toBeVisible();
    await expect(connectedDialog.getByRole('button', { name: 'Done', exact: true })).toBeFocused();
    await desktop.screenshot({ path: path.join(evidence, 'desktop-approved.png'), animations: 'disabled' });
    await expect.poll(badge).toBe('✓');
    const stored = await worker.evaluate(() => chrome.storage.local.get(['appToken', 'appTokenVersion']));
    expect(stored.appToken).toMatch(/^[0-9a-f]{64}$/);
    expect(stored.appToken).not.toBe(codeToken);
    expect(stored.appTokenVersion).toBe(2);
    await connectedDialog.getByRole('button', { name: 'Done', exact: true }).click();

    // The next popup opening celebrates once and clears the badge.
    popup = await context.newPage();
    await popup.goto(popupUrl);
    await expect(popup.locator('#sheet .pair-yay-title')).toHaveText('Connected');
    await expect(popup.locator('#sheet').getByRole('button', { name: 'Done', exact: true })).toBeFocused();
    await popup.screenshot({ path: path.join(evidence, 'extension-one-click-connected.png'), animations: 'disabled' });
    await expect.poll(badge).toBe('');
    await popup.getByRole('button', { name: 'Done', exact: true }).click();
    await expect(popup.locator('#connection-banner')).toBeHidden();
    await expect(setup.getByRole('list', { name: 'Connected browsers' }).getByRole('listitem')).toHaveCount(1);
    expect((await fetch(`${native.baseUrl}/v1/queue`)).status).toBe(401);

    // Reopening uses the credential produced by real pairing, not a test token.
    await popup.close();
    popup = await context.newPage();
    await popup.goto(popupUrl);
    await expect(popup.locator('#popup')).not.toHaveAttribute('aria-busy', 'true');
    await expect(popup.locator('#connection-banner')).toBeHidden();
    await expect(popup.locator('#sheet')).not.toBeVisible();

    // 5. Disconnect from the desktop; the popup learns its key is dead.
    await setup.getByRole('button', { name: `Disconnect ${extensionId.slice(0, 6)}…${extensionId.slice(-6)}`, exact: true }).click();
    await expect(setup).toContainText('Chrome stops sending downloads here');
    await desktop.screenshot({ path: path.join(evidence, 'desktop-disconnect-confirm.png'), animations: 'disabled' });
    await setup.getByRole('button', { name: 'Disconnect', exact: true }).click();
    await expect(setup).toContainText('Chrome is disconnected. Its key no longer works.');
    await expect(popup.locator('#connection-banner')).toContainText('Disconnected from SnagThis');
    expect((await fetch(`${native.baseUrl}/v1/queue`, { headers: { Authorization: `Bearer ${stored.appToken}` } })).status).toBe(401);
    fs.writeFileSync(path.join(evidence, 'result.json'), JSON.stringify({
      firstRunSetupVisible: true, explicitCodeGeneration: true, copyFeedback: true, offlineRecovery: true,
      oneClickDigitsMatch: true, allowDisabledAndUnfocusedOnOpen: true, denyLeavesDisconnected: true,
      codeFallbackConnected: true, invalidAndExpiredRejected: true, popupDisconnectRevokedKey: true,
      oneClickRepairSucceeded: true, perExtensionTokenDiffersFromDesktop: true, desktopDisconnectRevokedKey: true,
      unauthenticatedQueueRejected: true, screenshotsUseIsolatedProfiles: true,
    }, null, 2));
  } finally {
    try {
      if (clockShifted) {
        cleanupStage('restoring-clocks');
        await native?.app.evaluate(() => { if (globalThis.__pairingRealNow) { Date.now = globalThis.__pairingRealNow; delete globalThis.__pairingRealNow; } });
        if (desktop && !desktop.isClosed()) await desktop.evaluate(() => { if (window.__pairingRealNow) { Date.now = window.__pairingRealNow; delete window.__pairingRealNow; } });
      }
    } finally {
      try {
        cleanupStage('closing-chrome'); await context?.close();
      } finally {
        try {
          cleanupStage('closing-electron'); await native?.close();
        } finally {
          cleanupStage('closing-renderer'); await renderer.close();
          fs.rmSync(profile, { recursive: true, force: true });
          cleanupStage('complete');
        }
      }
    }
  }
});

// The popup's pairing states that the live flow above can't reach on demand (Cartridge,
// docs/design/prototypes/pairing-polish option 4), drawn by the shipped renderer in demo mode.
test('pairing sheet states: starting, expired, Web Store build and reduced motion', async () => {
  const evidence = path.join(root, 'work/verification/pairing-onboarding');
  fs.mkdirSync(evidence, { recursive: true });
  const browser = await chromium.launch({ channel: 'chromium', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 480, height: 560 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const open = async query => { await page.goto(`file://${path.join(root, 'apps/extension/popup.html')}?demo=pairing&${query}`); await expect(page.locator('#sheet')).toHaveCSS('opacity', '1'); };
    await open('pair=starting');
    await expect(page.locator('#sheet .pair-status')).toContainText('Asking SnagThis');
    await expect(page.locator('#sheet .pair-digits')).toHaveCount(0);
    await page.screenshot({ path: path.join(evidence, 'extension-state-starting.png'), animations: 'disabled' });
    await open('pair=expired');
    await expect(page.getByRole('alert')).toHaveText('Timed out');
    await expect(page.locator('#sheet')).toContainText('Nothing was connected.');
    await expect(page.locator('#sheet .action.primary')).toHaveText('Try again');
    await expect(page.locator('#sheet .pair-foot')).toContainText('Or use a code');
    await page.screenshot({ path: path.join(evidence, 'extension-state-expired.png'), animations: 'disabled' });
    await open('pair=denied');
    await expect(page.locator('#sheet .action.primary')).toHaveText('Use a code');
    await expect(page.locator('#sheet .pair-foot')).toHaveCount(0);
    await open('pair=waiting&build=store');
    await expect(page.locator('#sheet .pair-devchip')).toHaveCount(0);
    await expect(page.locator('#sheet .pair-pip.now')).toHaveCount(1);
    await page.screenshot({ path: path.join(evidence, 'extension-state-waiting-store.png'), animations: 'disabled' });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await open('pair=waiting');
    await expect(page.locator('#sheet .pair-devchip')).toHaveText('DEV BUILD');
    expect(await page.locator('#sheet .pair-digit').first().evaluate(node => getComputedStyle(node).animationName)).toBe('none');
    await page.screenshot({ path: path.join(evidence, 'extension-state-waiting-reduced.png') });
    await open('pair=connected');
    await expect(page.locator('#sheet .pair-yay-title')).toHaveText('Connected');
    await expect(page.locator('#sheet .pair-pips.good .pair-pip')).toHaveCount(12);
    await page.screenshot({ path: path.join(evidence, 'extension-state-connected.png') });
    expect(errors).toEqual([]);
  } finally {
    await browser.close();
  }
});
