// Desktop-only copy; shared row state copy lives in @m3u8/contracts/strings.
export const ui = {
  paste: 'Paste a video link', checking: 'Checking link…', all: 'All', downloading: 'Downloading', saved: 'Saved',
  search: 'Search', searchPlaceholder: 'Search your videos', closeSearch: 'Close search', settings: 'Settings',
  firstTitle: 'Download your first video', firstBody: 'Paste a link above, or play a video in Chrome and click the SnagThis icon in the toolbar.',
  addChrome: 'Add SnagThis to Chrome', chromeInstalled: 'Already installed? Connect Chrome', connectChrome: 'Connect Chrome', nothingDownloading: 'Nothing downloading', noSaved: 'No saved videos yet',
  noMatches: 'No videos match your search', loading: 'Loading your videos…', loadMore: 'Load more videos',
  more: 'More', details: 'Details', rename: 'Rename', copyLink: 'Copy link', openPage: 'Open page', showFolder: 'Show in folder',
  startNow: 'Start now', moveUp: 'Move up', moveDown: 'Move down', remove: 'Remove…', cancelDownload: 'Cancel download',
  removeTitle: 'Remove this video?', removeBody: 'Remove it from SnagThis, or move the saved file to your computer’s Trash.',
  removeList: 'Remove from list', keepFile: 'The file stays in your save folder.', trash: 'Move file to Trash', cancel: 'Cancel',
  cancelTitle: 'Cancel this download?', cancelBody: 'More than half of this video has downloaded. You can resume it with Undo.',
  cancelled: 'Download cancelled', undo: 'Undo', removed: 'Removed from list. Your file is still in its folder.', trashed: 'Moved file to Trash',
  linkCopied: 'Link copied', save: 'Save', saveFolder: 'Open save folder', pauseAll: 'Pause all', resumeAll: 'Resume all',
  quality: 'Quality', size: 'Size', from: 'From', savingTo: 'Saving to', savedIn: 'Saved in', problem: 'Problem', pieces: 'Segments', copied: 'Copied', trashAlso: 'Also removes it from the list', groupDownloads: 'Downloads', groupApp: 'App',
  openFolder: 'Open folder', locate: 'Locate', technicalDetails: 'Technical details', fileName: 'File name', fullPath: 'Full path',
  connectionsLabel: 'Connections', connectionsUsage: '{active} of {limit} active', connectionsUsageWithoutLimit: '{active} active', speedTrace: 'Download speed {speed}',
  connectionsUnavailable: 'Not reported by this downloader', connectionsLimit: 'limit {limit}',
  refreshLink: 'Use a new link', refreshPlaceholder: 'Paste the refreshed video link', replaceLink: 'Continue with this link',
  useChromeSession: 'Use Chrome sign-in', chromeSessionTitle: 'Use your Chrome sign-in for this video?',
  chromeSessionBody: 'Allow the downloader to read your local Chrome cookies and use your signed-in YouTube session for this download. SnagThis does not save the cookies in your library or diagnostics.',
  chromeSessionHint: 'You must already be able to play this video in Chrome. Your system may ask for access to Chrome’s saved sign-in.',
  downloadingError: 'SnagThis couldn’t finish that action. Try again.', startup: 'Starting SnagThis…',
  unavailable: 'SnagThis couldn’t connect to your downloads.', tryAgain: 'Try again',
  saveVideosTo: 'Save videos to', change: 'Change', preferredQuality: 'Preferred quality', subtitles: 'Subtitles',
  best: 'Best', none: 'None', notify: 'Tell me when a download finishes', login: 'Start SnagThis when I log in',
  advanced: 'Advanced', atOnce: 'Downloads at once', connections: 'Connections per download', autoStart: 'Start new downloads right away',
  naming: 'File naming', titleNaming: 'Video title', resourceNaming: 'Name from link', customNaming: 'My own name',
  customFilename: 'Name for new downloads', tmdbKey: 'TMDB API key', subdlKey: 'SubDL API key',
  showKey: 'Show key', hideKey: 'Hide key', checkStartup: 'Check for updates on startup',
  updates: 'Updates', checkUpdates: 'Check for updates', install: 'Restart & install', later: 'Later (30 min)',
  diagnostics: 'Diagnostics', exportDiagnostics: 'Export support bundle', copyDiagnostics: 'Copy diagnostics',
  clearTemp: 'Clear temporary download data', chrome: 'Chrome extension',
  pairingHelp: 'Paste this code in the SnagThis extension.',
  closeSettings: 'Close settings', sampleData: 'Design gallery · sample videos', download: 'Download',
  reportSite: 'Report a site that didn’t work', reportTitle: 'Site compatibility report',
  reportPreview: 'The issue form will include only a redacted download summary.',
  reportOpenError: 'Could not open the issue form', reportInstructions: 'Describe what happened and what you expected. Add a public site name if useful. Do not include signed video links, cookies or access tokens.',
  reportSummary: 'Redacted download summary', reportStages: 'Stages to check', reportNotChecked: 'Not checked',
  reportStagePage: 'Page opens', reportStageDetection: 'Video detected', reportStageRow: 'Correct video shown',
  reportStageQuality: 'Quality choices found', reportStageFetch: 'Source fetched', reportStageDownload: 'Download completed', reportStagePlayback: 'Saved file plays',
  galleryVideoDescription: 'Play a short sample from this Blender open movie.',
  subtitlesUnavailable: 'no {lang} subtitles found', actionBusy: 'Wait for the current action on this video to finish.',
  resumeDownload: 'Resume download', dragToReorder: 'Drag to reorder', technicalDetail: 'Technical detail',
  expiredPageOpened: 'Play the video in Chrome, then click SnagThis to continue from {percent}%.',
  pairingSteps: ['Show a code here and copy it.', 'In Chrome, click Extensions (the puzzle icon) → SnagThis → Connect.', 'Paste the code there and choose Connect.'],
  firstPairingSteps: ['Add SnagThis to Chrome with the button above.', 'Choose Connect Chrome below to show a connection code.', 'In Chrome, click Extensions (the puzzle icon) → SnagThis → Connect, then paste the code.'],
  atOnceHint: '1–16 · more downloads share your connection', connectionsHint: '1–16 · more can speed up segmented videos',
  tmdbHint: 'Optional · adds posters and movie or TV names to files', subdlHint: 'Optional · finds subtitles a site doesn’t provide',
  settingSaved: 'Saved', savedAnnouncement: '{label} saved', settingsDescription: 'Choose how SnagThis saves your videos. Changes save automatically.',
  closeSettingsHint: 'Close (Esc)', changeFolder: 'Change…', changeFolderLabel: 'Change save folder', openFolderShort: 'Open', defaultFolder: 'Downloads/SnagThis (default)',
  qualityHint: 'When a video offers a choice', subtitlesHint: 'Saved with the video if offered',
  numberRange: 'Enter a whole number from {min} to {max}.', decrease: 'Decrease {label}', increase: 'Increase {label}',
  advancedSpeed: 'Speed', advancedNames: 'File names', advancedLookups: 'Online lookups',
  autoStartHint: 'When off, new downloads wait until you start them',
  titleNamingHint: 'Uses the video’s title from the page', resourceNamingHint: 'Uses the file name in the video link', customNamingHint: 'Uses the name below for every new download',
  customFilenameHint: 'Repeats get (2), (3)… Existing files are not renamed.', customFilenamePlaceholder: 'e.g. Lecture', customFilenameSlash: 'A name can’t contain / or \\.', customFilenameLong: 'Use 200 characters or fewer.',
  restoreDefaults: 'Restore default speed and file names', usingDefaults: 'Speed and file names use the defaults', keyPlaceholder: 'Not set',
  updatesInstalledOnly: 'Update checks work in the installed app.',
  settingsSections: 'Settings sections', chromeSectionHint: 'Send videos from Chrome to this app.', downloadsSectionHint: 'Where videos go and which version you get.',
  appSectionHint: 'Notifications and start-up.', appearance: 'Appearance', appearanceSectionHint: 'How SnagThis looks.',
  advancedSectionHint: 'Speed, file names and online lookups.', updatesSupport: 'Updates & support', updatesSupportSectionHint: 'Version, updates and diagnostics.',
  accentColour: 'Accent colour', accentHint: 'Buttons, focus and highlights use this colour.', appVersion: 'SnagThis {version}',
  listView: 'List view', shelfView: 'Shelf view', savedView: 'Saved view', savedShelf: 'Saved videos', play: 'Play',
  commands: 'Commands', commandPalette: 'Command palette', paletteHint: 'Type a command, a video, or paste a link',
  paletteNoMatches: 'No matches', paletteGroupLink: 'Link', paletteGroupActions: 'Actions', paletteGroupGoTo: 'Go to',
  paletteGroupSettings: 'Settings', paletteGroupAppearance: 'Appearance', paletteGroupVideos: 'Videos',
  paletteSnagLink: 'Snag this link', palettePasteLink: 'Paste a video link', paletteClipboard: 'Download link from clipboard',
  paletteClipboardEmpty: 'No video link on the clipboard', palettePauseAll: 'Pause all downloads', paletteResumeAll: 'Resume all downloads',
  paletteSearch: 'Search videos', paletteGoTo: 'Go to {tab}', paletteShelf: 'Show Saved as a shelf', paletteList: 'Show Saved as a list',
  paletteSettings: 'Open Settings', paletteSettingsSection: 'Settings: {section}', paletteAccent: 'Accent colour: {name}',
  paletteMove: 'move', paletteRun: 'run', paletteClose: 'close',
  dropTitle: 'Drop to', dropHint: 'One link or many — each becomes a row', dropChecking: 'Checking the dropped link…',
  dropAdded: 'Dropped link added to your downloads', dropChoose: 'Choose a quality for the dropped video', dropBusy: 'Wait for the current link check to finish, then drop again.',
  renderFailed: 'Something went wrong.', renderFailedBody: 'Downloads keep running in the background. Reload to reopen the window.', reload: 'Reload', copyDetails: 'Copy details',
} as const;
