// Desktop-only copy; shared row state copy lives in @m3u8/contracts/strings.
export const ui = {
  paste: 'Paste a video link', checking: 'Checking link…', all: 'All', downloading: 'Downloading', saved: 'Saved',
  search: 'Search', searchPlaceholder: 'Search your videos', closeSearch: 'Close search', settings: 'Settings',
  firstTitle: 'Download your first video', firstBody: 'Paste a link above, or play a video in Chrome and click the VidSnag icon in the toolbar.',
  addChrome: 'Add VidSnag to Chrome', chromeInstalled: 'Already installed? Connect Chrome', connectChrome: 'Connect Chrome', nothingDownloading: 'Nothing downloading', noSaved: 'No saved videos yet',
  noMatches: 'No videos match your search', loading: 'Loading your videos…', loadMore: 'Load more videos',
  more: 'More', details: 'Details', rename: 'Rename', copyLink: 'Copy link', openPage: 'Open page', showFolder: 'Show in folder',
  startNow: 'Start now', moveUp: 'Move up', moveDown: 'Move down', remove: 'Remove…', cancelDownload: 'Cancel download',
  removeTitle: 'Remove this video?', removeBody: 'Remove it from VidSnag, or move the saved file to your computer’s Trash.',
  removeList: 'Remove from list', keepFile: 'The file stays in your save folder.', trash: 'Move file to Trash', cancel: 'Cancel',
  cancelTitle: 'Cancel this download?', cancelBody: 'More than half of this video has downloaded. You can resume it with Undo.',
  cancelled: 'Download cancelled', undo: 'Undo', removed: 'Removed from list. Your file is still in its folder.', trashed: 'Moved file to Trash',
  linkCopied: 'Link copied', save: 'Save', saveFolder: 'Open save folder', pauseAll: 'Pause all', resumeAll: 'Resume all',
  quality: 'Quality', size: 'Size', from: 'From', savingTo: 'Saving to', savedIn: 'Saved in', problem: 'Problem', pieces: 'Segments', copied: 'Copied', trashAlso: 'Also removes it from the list', groupDownloads: 'Downloads', groupApp: 'App', groupMore: 'More', advancedHint: 'Speed, naming, accounts, updates',
  openFolder: 'Open folder', locate: 'Locate', technicalDetails: 'Technical details', fileName: 'File name', fullPath: 'Full path',
  connectionsLabel: 'Connections', connectionsUsage: '{active} of {limit} active', connectionsUsageWithoutLimit: '{active} active',
  connectionsUnavailable: 'Not reported by this downloader', connectionsLimit: 'limit {limit}',
  refreshLink: 'Use a new link', refreshPlaceholder: 'Paste the refreshed video link', replaceLink: 'Continue with this link',
  useChromeSession: 'Use Chrome sign-in', chromeSessionTitle: 'Use your Chrome sign-in for this video?',
  chromeSessionBody: 'Allow the downloader to read your local Chrome cookies and use your signed-in YouTube session for this download. VidSnag does not save the cookies in your library or diagnostics.',
  chromeSessionHint: 'You must already be able to play this video in Chrome. Your system may ask for access to Chrome’s saved sign-in.',
  downloadingError: 'VidSnag couldn’t finish that action. Try again.', startup: 'Starting VidSnag…',
  unavailable: 'VidSnag couldn’t connect to your downloads.', tryAgain: 'Try again',
  saveVideosTo: 'Save videos to', change: 'Change', preferredQuality: 'Preferred quality', subtitles: 'Subtitles',
  best: 'Best', none: 'None', notify: 'Tell me when a download finishes', login: 'Start VidSnag when I log in',
  advanced: 'Advanced', atOnce: 'Downloads at once', connections: 'Connections per download', autoStart: 'Start automatically',
  naming: 'File naming', titleNaming: 'Page title', resourceNaming: 'Resource filename', customNaming: 'Custom name',
  customFilename: 'Custom filename', tmdbKey: 'TMDB API key', subdlKey: 'SubDL API key',
  showKey: 'Show key', hideKey: 'Hide key', checkStartup: 'Check for updates on startup',
  updates: 'Updates', checkUpdates: 'Check for updates', install: 'Restart & install', later: 'Later (30 min)',
  diagnostics: 'Diagnostics', exportDiagnostics: 'Export support bundle', copyDiagnostics: 'Copy diagnostics',
  clearTemp: 'Clear temporary download data', chrome: 'Chrome extension',
  pairingHelp: 'Paste this code in the VidSnag extension.',
  closeSettings: 'Close settings', sampleData: 'Design gallery · sample videos', download: 'Download',
  reportSite: 'Report a site that didn’t work', reportTitle: 'Site compatibility report',
  reportPreview: 'The issue form will include only a redacted download summary.',
  reportOpenError: 'Could not open the issue form', reportInstructions: 'Describe what happened and what you expected. Add a public site name if useful. Do not include signed video links, cookies or access tokens.',
  reportSummary: 'Redacted download summary', reportStages: 'Stages to check', reportNotChecked: 'Not checked',
  reportStagePage: 'Page opens', reportStageDetection: 'Video detected', reportStageRow: 'Correct video shown',
  reportStageQuality: 'Quality choices found', reportStageFetch: 'Source fetched', reportStageDownload: 'Download completed', reportStagePlayback: 'Saved file plays',
  galleryVideoDescription: 'Play a short sample from this Blender open movie.',
} as const;
