// Desktop-only copy; shared row state copy lives in @m3u8/contracts/strings.
export const ui = {
  paste: 'Paste a video link', checking: 'Checking link…', all: 'All', downloading: 'Downloading', saved: 'Saved',
  search: 'Search', searchPlaceholder: 'Search your videos', closeSearch: 'Close search', settings: 'Settings',
  firstTitle: 'Download your first video', firstBody: 'Paste a link above, or play a video in Chrome and click the SnagThis icon in the toolbar.',
  addChrome: 'Add SnagThis to Chrome', connectChrome: 'Connect Chrome', nothingDownloading: 'Nothing downloading', noSaved: 'No saved videos yet',
  noMatches: 'No videos match your search', loading: 'Loading your videos…', loadMore: 'Load more videos',
  more: 'More', details: 'Details', rename: 'Rename', copyLink: 'Copy link', openPage: 'Open page', showFolder: 'Show in folder',
  startNow: 'Start now', moveUp: 'Move up', moveDown: 'Move down', remove: 'Remove…', cancelDownload: 'Cancel download',
  removeTitle: 'Remove this video?', removeBody: 'Remove it from SnagThis, or move the saved file to your computer’s Trash.',
  removeList: 'Remove from list', keepFile: 'The file stays in your save folder.', trash: 'Move file to Trash', cancel: 'Cancel',
  cancelTitle: 'Cancel this download?', cancelBody: 'More than half of this video has downloaded. You can resume it with Undo.',
  cancelled: 'Download cancelled', undo: 'Undo', removed: 'Removed from list. Your file is still in its folder.', trashed: 'Moved file to Trash',
  linkCopied: 'Link copied', save: 'Save', saveFolder: 'Open save folder', pauseAll: 'Pause all', resumeAll: 'Resume all',
  quality: 'Quality', size: 'Size', from: 'From', savingTo: 'Saving to', savedIn: 'Saved in', problem: 'Problem', pieces: 'Segments', copied: 'Copied', trashAlso: 'Also removes it from the list', groupDownloads: 'Downloads', groupApp: 'App',
  openFolder: 'Open folder', locate: 'Locate', technicalDetails: 'Technical details', fileName: 'File name', fullPath: 'Full path',
  connectionsLabel: 'Connections', connectionsUsage: '{active} of {limit} active', connectionsUsageWithoutLimit: '{active} active', speedTrace: 'Download speed {speed}',
  connectionsUnavailable: 'Not reported by this downloader', connectionsLimit: 'limit {limit}',
  refreshLink: 'Use a new link', refreshPlaceholder: 'Paste the refreshed video link', replaceLink: 'Continue with this link',
  useChromeSession: 'Use Chrome sign-in', chromeSessionTitle: 'Use your Chrome sign-in for this video?',
  chromeSessionBody: 'Allow the downloader to read your local Chrome cookies and use your signed-in YouTube session for this download. SnagThis does not save the cookies in your library or diagnostics.',
  chromeSessionHint: 'You must already be able to play this video in Chrome. Your system may ask for access to Chrome’s saved sign-in.',
  downloadingError: 'SnagThis couldn’t finish that action. Try again.', startup: 'Starting SnagThis…',
  unavailable: 'SnagThis couldn’t connect to your downloads.', tryAgain: 'Try again',
  saveVideosTo: 'Save videos to', change: 'Change', preferredQuality: 'Preferred quality', subtitles: 'Subtitles',
  best: 'Best', none: 'None', notify: 'Tell me when a download finishes', login: 'Start SnagThis when I log in',
  advanced: 'Advanced', atOnce: 'Downloads at once', connections: 'Connections per download', autoStart: 'Start new downloads right away',
  naming: 'Name new files by', titleNaming: 'Video title', resourceNaming: 'Name from link', customNaming: 'My own name',
  customFilename: 'Name for new downloads', tmdbKey: 'TMDB key', subdlKey: 'SubDL key',
  showKey: 'Show key', hideKey: 'Hide key', checkStartup: 'Check automatically', checkStartupHint: 'Looks for a new version each time SnagThis starts.',
  updates: 'Updates', checkUpdates: 'Check now',
  // Updates, option B · Install on quit or idle (spec §8.1): the header chip and its popover, the
  // "Updated to" toast, and the Settings summary row.
  restartNow: 'Restart now', updateAfterOne: 'After 1 download finishes', updateAfterMany: 'After {n} downloads finish',
  updateChipReady: 'ready', updateChipReadyLabel: 'SnagThis {version} is ready. Show update',
  updateChipRestarting: 'Restarting…', updateChipRestartingLabel: 'Restarting to install SnagThis {version}',
  updateChipFailedInstall: '{version} didn’t install', updateChipFailedDownload: '{version} didn’t download', updateChipFailedLabel: 'SnagThis {version} didn’t update. Show details',
  updatePopoverTitle: 'SnagThis {version} is ready', updatePopoverLine: 'Installs next time you quit SnagThis, or restart now.',
  updatedToast: 'Updated to {version}', updateWhatsNew: 'What’s new', updateWhatsNewIn: 'What’s new in {version}', updateFullNotes: 'Full release notes',
  updateTagNew: 'New', updateTagBetter: 'Better', updateTagFixed: 'Fixed', updateClose: 'Close',
  updateChecking: 'Checking for updates…', updateJustNow: 'just now', updateMinutesAgo: '{n} min ago', updateAtTime: 'at {time}',
  updateBytes: '{done} of {total} MB', updateBytesDone: '{done} MB',
  updateErrorDownload: 'Couldn’t download {version}', updateErrorCheck: 'Couldn’t check for updates', updateErrorInstall: 'Couldn’t install {version}', updateErrorLocation: 'SnagThis can’t update from this folder',
  updateDroppedAt: 'The connection dropped at {bytes}.', updateDownloadStopped: 'The download stopped before it finished.', updateCheckFailed: 'SnagThis couldn’t reach the update service.',
  updateInstallFailed: 'The installer didn’t finish.', updateMoveApp: 'Move SnagThis to your Applications folder, then try again.',
  updateNothingChanged: 'You’re still on {version}; nothing changed.', updateDownloadInstaller: 'Download installer', updateTryAgain: 'Try again', updateDetails: 'Details', updateHideDetails: 'Hide details', updateTechnical: 'Technical detail',
  updateHintUpToDate: 'Up to date · checked {when}', updateHintDownloading: 'Downloading {version} · {bytes}', updateHintDownloadingPlain: 'Downloading {version}…',
  updateHintReady: '{version} ready', updateHintInstalling: 'Restarting to install {version}…', updateHintError: 'Couldn’t update',
  updateHintMove: 'Updates need SnagThis in your Applications folder.', moveToApplications: 'Move to Applications',
  diagnostics: 'Support', supportBundle: 'Support bundle', supportBundleHint: 'Logs and settings for a bug report. Keys are left out.', exportDiagnostics: 'Export…', exportDiagnosticsLabel: 'Export support bundle', copyDiagnostics: 'Copy', copyDiagnosticsLabel: 'Copy diagnostics',
  clearTemp: 'Clear', clearTempLabel: 'Clear temporary download data', tempData: 'Temporary download data', tempDataHint: 'Parts left behind by cancelled or failed downloads.', chrome: 'Chrome extension',
  closeSettings: 'Close settings', sampleData: 'Design gallery · sample videos', download: 'Download',
  reportSite: 'Report', reportSiteLabel: 'Report a site that didn’t work', reportSiteTitle: 'A site didn’t work?', reportSiteHint: 'Opens a GitHub issue with a summary. No links or file names.', reportTitle: 'Site compatibility report',
  reportPreview: 'The issue form will include only a redacted download summary.',
  reportOpenError: 'Could not open the issue form', reportInstructions: 'Describe what happened and what you expected. Add a public site name if useful. Do not include signed video links, cookies or access tokens.',
  reportSummary: 'Redacted download summary', reportStages: 'Stages to check', reportNotChecked: 'Not checked',
  reportStagePage: 'Page opens', reportStageDetection: 'Video detected', reportStageRow: 'Correct video shown',
  reportStageQuality: 'Quality choices found', reportStageFetch: 'Source fetched', reportStageDownload: 'Download completed', reportStagePlayback: 'Saved file plays',
  galleryVideoDescription: 'Play a short sample of this animation.',
  subtitlesUnavailable: 'no {lang} subtitles found', actionBusy: 'Wait for the current action on this video to finish.',
  resumeDownload: 'Resume download', dragToReorder: 'Drag to reorder', technicalDetail: 'Technical detail',
  expiredPageOpened: 'Play the video in Chrome, then click SnagThis to continue from {percent}%.',
  // Pair from the desktop (pairing-simple option B): the connect card waits for Chrome, then asks in place.
  chromeCardHintBefore: 'Click ', chromeCardHintAfter: ' in Chrome’s toolbar', chromeWaiting: 'Waiting for Chrome…',
  chromeWaitingAnother: 'Waiting for a browser… open SnagThis there', chromeCardInstall: 'Don’t have it yet? Add SnagThis to Chrome',
  pairingCardTitle: 'Chrome wants to connect', pairingConnectedCard: 'Connected', chromeConnectButton: 'Connect Chrome', chromeListenHint: 'Then open SnagThis in that browser. It asks here, and you choose Allow.',
  atOnceHint: 'Others wait their turn. More at once share your bandwidth.', connectionsHint: 'More can speed up videos that arrive in segments.', numberBounds: '{min}–{max}',
  tmdbHint: 'Optional. Adds posters and proper movie or TV names.', subdlHint: 'Optional. Finds subtitles when a site has none.',
  settingSaved: 'Saved', savedAnnouncement: '{label} saved', settingsDescription: 'Choose how SnagThis saves your videos. Changes save automatically.',
  closeSettingsHint: 'Close (Esc)', changeFolder: 'Change…', changeFolderLabel: 'Change save folder', openFolderShort: 'Open folder', defaultFolder: '~/Downloads/SnagThis', defaultTag: 'Default',
  qualityHint: 'Used when a video comes in more than one size.', subtitlesHint: 'Saved next to the video when the site has them.',
  numberRange: 'Enter a whole number from {min} to {max}.', decrease: 'Decrease {label}', increase: 'Increase {label}',
  advancedSpeed: 'Speed', advancedNames: 'File names', advancedLookups: 'Online lookups', groupSaving: 'Saving', groupQuality: 'Quality', groupNotifications: 'Notifications', groupStartup: 'Start-up',
  notifyHint: 'Shows a system notification with the video’s name.', loginHint: 'Chrome can only send videos while SnagThis is open.', autosaveNote: 'Changes save as you make them.',
  autoStartHint: 'When off, new downloads wait until you start them.',
  titleNamingHint: 'Uses the video’s title from the page', resourceNamingHint: 'Uses the file name in the video link', customNamingHint: 'Uses the name below for every new download',
  customFilenameHint: 'Repeats get (2), (3)… Existing files are not renamed.', customFilenamePlaceholder: 'e.g. Lecture', customFilenameSlash: 'A name can’t contain / or \\.', customFilenameLong: 'Use 200 characters or fewer.',
  restoreDefaults: 'Restore defaults', restoreDefaultsLabel: 'Restore defaults for speed and file names', restoreDefaultsNote: 'Restore defaults resets speed and file names. Your API keys stay.', usingDefaults: 'Using defaults', usingDefaultsLabel: 'Using defaults for speed and file names', keyPlaceholder: 'Not set',
  updatesInstalledOnly: 'Update checks work in the installed app.', updatesNotChecked: 'Not checked yet',
  settingsSections: 'Settings sections', chromeSectionHint: 'Send videos from Chrome to SnagThis with one click.', downloadsSectionHint: 'Where videos are saved, and which version SnagThis picks.',
  appSectionHint: 'Notifications, and whether SnagThis opens when you log in.', appearance: 'Appearance', appearanceSectionHint: 'How SnagThis looks here and in the Chrome extension.',
  advancedSectionHint: 'Speed, file names and online lookups. The defaults suit most people.', updatesSupport: 'Updates & support', updatesSupportSectionHint: 'Keep SnagThis up to date, and get help when a site doesn’t work.',
  accentColour: 'Accent colour', accentHint: 'Used for buttons, focus rings and highlights. The Chrome extension follows it too.', appVersion: 'SnagThis {version}',
  listView: 'List view', shelfView: 'Shelf view', savedView: 'Saved view', savedShelf: 'Saved videos', play: 'Play',
  commands: 'Commands', commandPalette: 'Command palette', paletteHint: 'Type a command, a video, or paste a link',
  paletteNoMatches: 'No matches', paletteGroupLink: 'Link', paletteGroupActions: 'Actions', paletteGroupGoTo: 'Go to',
  paletteGroupSettings: 'Settings', paletteGroupAppearance: 'Appearance', paletteGroupVideos: 'Videos',
  paletteSnagLink: 'Snag this link', palettePasteLink: 'Paste a video link', paletteClipboard: 'Download link from clipboard',
  paletteClipboardEmpty: 'No video link on the clipboard', palettePauseAll: 'Pause all downloads', paletteResumeAll: 'Resume all downloads',
  paletteSearch: 'Search videos', paletteGoTo: 'Go to {tab}', paletteShelf: 'Show Saved as a shelf', paletteList: 'Show Saved as a list',
  paletteSettings: 'Open Settings', paletteSettingsSection: 'Settings: {section}', paletteAccent: 'Accent colour: {name}',
  paletteMove: 'move', paletteRun: 'run', paletteClose: 'close',
  dropTitle: 'Drop to', dropHint: 'One link or many — each becomes a row', dropChecking: 'Checking the dropped link…',
  dropAdded: 'Dropped link added to your downloads', dropChoose: 'Choose a quality for the dropped video', dropBusy: 'Wait for the current link check to finish, then drop again.',
  ok: 'OK', done: 'Done', allow: 'Allow', deny: 'Deny',
  pairingMatchLabel: 'Match code', pairingDialogTitle: 'Connect Chrome?',
  pairingDialogBody: 'Allow only if Chrome shows the same digits.',
  pairingExpiresIn: 'Expires in {time}', pairingMismatchHint: 'Different digits? Choose Deny.',
  pairingOneMinute: '1 minute left to choose.', pairingFifteenSeconds: '15 seconds left to choose.',
  pairingStoreName: 'SnagThis for Chrome', pairingUnknownName: 'Chrome extension',
  pairingStoreBuild: '✓ Web Store', pairingNotStore: 'Not Web Store',
  pairingNotStoreHint: 'Loaded unpacked or from outside the Chrome Web Store. The digits are the real check.', pairingConnectedBefore: 'Connected here before',
  pairingConflictTitle: 'Two connection requests at once',
  pairingConflictBody: 'Chrome and something else asked within the same few seconds. SnagThis cancelled both so the wrong one can’t get in.',
  pairingConnectedTitle: 'Chrome connected', pairingConnectedBody: 'Downloads from Chrome now arrive here.',
  pairingDeniedToast: 'Chrome wasn’t connected. It can ask again in an hour.',
  pairingExpiredToast: 'Chrome’s request timed out. Nothing was connected.',
  pairingCancelledToast: 'Chrome cancelled its connection request.',
  pairingWaiting: 'Chrome is asking to connect', pairingReview: 'Review', pairingWaitingHint: 'Check that Chrome shows the same four digits · expires in {time}',
  chromeStatus: 'Status', chromeConnectGroup: 'Connect Chrome', chromeConnectAnother: 'Connect another browser',
  chromeConnectedTo: 'Connected to {name}', chromeNotConnected: 'Chrome isn’t connected', chromeNotConnectedHint: 'Connect once, then send any video from Chrome with one click.',
  chromeDisconnectedHint: 'Chrome is disconnected. Its key no longer works.', chromeConnectedFallbackHint: 'Keep SnagThis open while downloading.', chromeIsConnected: 'Chrome is connected',
  chromeKeysNote: 'Each browser gets its own key, so disconnecting one leaves the others connected.', chromeAddToChrome: 'Add to Chrome',
  chromeDisconnectTitle: 'Disconnect {name}?', chromeDisconnectBody: 'Chrome stops sending downloads here until you connect it again. Finished files and your library stay.',
  chromeUseCode: 'Use a code instead', chromeUseCodeHint: 'If Chrome doesn’t connect on its own, or for another browser.', chromeCodeHint: 'Paste it in the SnagThis popup. Expires in {time}.', chromeCodeExpired: 'This code expired. Get a new code and try again.',
  renderFailed: 'Something went wrong.', renderFailedBody: 'Downloads keep running in the background. Reload to reopen the window.', reload: 'Reload', copyDetails: 'Copy details',
} as const;
