const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const { Writable } = require('node:stream');
const { createTransferMetrics } = require('../packages/downloader-engine/src/core/TransferMetrics');
const { downloadSegment } = require('../packages/downloader-engine/src/core/SegmentDownloader');

test('transfer metrics count overlapping work and finish each transfer only once', () => {
  const job = {};
  const metrics = createTransferMetrics(job, { maxConnections: 8 });
  const endFirst = metrics.begin();
  const endSecond = metrics.begin();
  assert.equal(job.activeConnections, 2);
  assert.equal(job.maxConnections, 8);
  assert.equal(job.connectionCountAvailable, true);
  endFirst();
  endFirst();
  assert.equal(job.activeConnections, 1);
  endSecond();
  assert.equal(job.activeConnections, 0);
});

test('unobservable transfer counts stay unavailable rather than showing a fabricated zero', () => {
  const job = { speedBps: 500, etaSeconds: 12 };
  const metrics = createTransferMetrics(job, { maxConnections: 4, available: false });
  const end = metrics.begin();
  metrics.recordBytes(1000);
  end();
  metrics.finish();
  assert.equal(job.activeConnections, null);
  assert.equal(job.connectionCountAvailable, false);
  assert.equal(job.maxConnections, 4);
  assert.equal(job.speedBps, 500, 'external progress keeps ownership of its speed');
  assert.equal(job.etaSeconds, 12);
});

test('segmented transfers report received-byte speed while active and clear it after success or retry failure', { timeout: 5000 }, async (t) => {
  const responses = new Map();
  let requestCount = 0;
  let twoRequests;
  let retryRequest;
  const received = new Promise((resolve) => { twoRequests = resolve; });
  const retried = new Promise((resolve) => { retryRequest = resolve; });
  const server = http.createServer((request, response) => {
    responses.set(request.url, response);
    requestCount += 1;
    if (requestCount === 2) twoRequests();
    if (requestCount === 3) retryRequest();
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise((resolve) => { server.closeAllConnections(); server.close(resolve); }));
  const url = `http://127.0.0.1:${server.address().port}`;
  let time = 0;
  const job = { url, bytesDownloaded: 0, totalBytes: 40 };
  job._transferMetrics = createTransferMetrics(job, { maxConnections: 2, now: () => time });
  let firstChunk;
  const streamed = new Promise(resolve => { firstChunk = resolve; });
  const sink = () => new Writable({ write(_chunk, _encoding, callback) { firstChunk(); callback(); } });
  const first = downloadSegment(`${url}/first.ts`, {}, sink(), job);
  const second = downloadSegment(`${url}/second.ts`, {}, sink(), job);
  const failed = assert.rejects(second, /status 503/);
  await received;
  assert.equal(job.activeConnections, 2);
  time = 1000;
  responses.get('/first.ts').write('fixture ');
  await streamed;
  assert.equal(job.bytesDownloaded, 8);
  assert.equal(job.speedBps, 8, 'received bytes produce speed before the transfer finishes');
  assert.equal(job.etaSeconds, 4, 'known remaining bytes use the measured rate');
  responses.get('/second.ts').writeHead(503).end('Temporary fixture failure');
  await failed;
  assert.equal(job.activeConnections, 1);
  assert.equal(job.bytesDownloaded, 8, 'an HTTP error body is not counted as media');
  const retry = downloadSegment(`${url}/second.ts`, {}, sink(), job);
  await retried;
  time = 2000;
  job.totalBytes = 0;
  responses.get('/second.ts').end('retry');
  await retry;
  assert.equal(job.bytesDownloaded, 13, 'retry bytes are recorded exactly once');
  assert.equal(job.speedBps, 6.5, 'overlapping transfers contribute to one measured rate');
  assert.equal(job.etaSeconds, null, 'unknown total size cannot produce a fabricated ETA');
  time = 3000;
  responses.get('/first.ts').end('media');
  await first;
  assert.equal(job.bytesDownloaded, 18);
  assert.equal(job.activeConnections, 0);
  assert.equal(job.speedBps, 0);
  assert.equal(job.etaSeconds, null);
  job.status = 'completed';
  job._transferMetrics.finish();
  assert.equal(job.etaSeconds, 0);
});
