#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { chromium } = require('@playwright/test');
const { startFixtureServer } = require('../tests/fixtures/server');
const { downloadMedia, probeFile } = require('../tests/fixtures/engine');

const ROOT = path.resolve(__dirname, '..');
const STAGES = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'];
const seeds = () => JSON.parse(fs.readFileSync(path.join(__dirname, 'sites.yaml'), 'utf8'));
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function redacted(message) {
  return String(message || '').replace(/https?:\/\/[^\s)"']+/g, (candidate) => {
    try { const url = new URL(candidate); return `${url.origin}/[redacted-path]`; } catch { return '[redacted-url]'; }
  }).replace(/(authorization|cookie|token|signature|key)\s*[:=]\s*[^\s,;]+/gi, '$1=[redacted]');
}

function buildMatrix(entries, results) {
  const latest = new Map();
  for (const result of results) latest.set(result.id, result);
  const mark = (result, stage) => result?.stages?.[stage]?.status === 'pass' ? '✓' : result?.stages?.[stage]?.status === 'fail' ? '✗' : result?.stages?.[stage]?.status === 'na' ? 'n/a' : '—';
  const rows = entries.map((entry) => {
    const result = latest.get(entry.id);
    return `| ${entry.id} | ${STAGES.map((stage) => mark(result, stage)).join(' | ')} | ${result?.checkedAt?.slice(0, 10) || 'Not run'} | ${result ? `${result.extensionVersion} / ${result.appVersion}` : '—'} | ${(entry.tags || []).join(', ')} |`;
  });
  const tags = [...new Set(entries.flatMap((entry) => entry.tags || []))].sort();
  const byTag = tags.map((tag) => {
    const grouped = entries.filter((entry) => entry.tags?.includes(tag));
    const tested = grouped.filter((entry) => latest.get(entry.id)?.stages?.S7?.status !== undefined && latest.get(entry.id)?.stages?.S7?.status !== 'unknown');
    const passed = tested.filter((entry) => latest.get(entry.id)?.stages?.S7?.status === 'pass');
    return `| ${tag} | ${passed.length}/${tested.length} tested | ${grouped.length - tested.length} |`;
  });
  const failures = [...latest.values()].filter((result) => result.failedStage).map((result) => `- ${result.id}: ${result.failedStage} — ${redacted(result.stages[result.failedStage].message)}. Issue: ${result.issue || 'not filed'}.`);
  return `# Compatibility evidence\n\nGenerated by \`node compat/run.js\`. ✓ passed, ✗ failed, — not tested, n/a not applicable. Source reachability in sites.yaml is not a product compatibility result. Direct stream seeds run in a local player and do not establish compatibility of their publisher's website.\n\n| Source | ${STAGES.join(' | ')} | Last run | Extension / app | Techniques |\n|---|${STAGES.map(() => '---').join('|')}|---|---|---|\n${rows.join('\n')}\n\n## By technique\n\n| Technique | S7 passing | Not tested |\n|---|---|---|\n${byTag.join('\n')}\n\n## Failures\n\n${failures.length ? failures.join('\n') : 'No failures in the latest recorded result for each source. This is not a claim that untested entries pass.'}\n\nStages: S1 page/player, S2 detection, S3 row grouping, S4 variants, S5 fetch context, S6 bounded engine download, S7 ffprobe, S8 full download (opt-in).\n`;
}

async function firstSegmentCheck(mediaUrl, headers) {
  let url = mediaUrl;
  const credentialOrigin = new URL(mediaUrl).origin;
  for (let depth = 0; depth < 4; depth++) {
    const scopedHeaders = Object.fromEntries(Object.entries(headers).filter(([name]) => new URL(url).origin === credentialOrigin || !/^(authorization|cookie|proxy-authorization|x-api-key)$/i.test(name)));
    const response = await fetch(url, { headers: scopedHeaders, signal: AbortSignal.timeout(10_000) });
    if (!response.ok) throw new Error(`Media request returned ${response.status}`);
    const type = response.headers.get('content-type') || '';
    if (!/mpegurl|m3u8/i.test(type + url)) { await response.body?.cancel(); return; }
    const text = await response.text();
    const resource = text.split(/\r?\n/).find((line) => line.trim() && !line.startsWith('#'));
    if (!resource) throw new Error('Playlist contained no media resource');
    url = new URL(resource, response.url).href;
  }
  throw new Error('Playlist nesting exceeded four levels');
}

async function runSite({ context, worker, fixture, entry, full, outputDirectory }) {
  const versions = {
    extensionVersion: JSON.parse(fs.readFileSync(path.join(ROOT, 'apps/extension/manifest.json'))).version,
    appVersion: JSON.parse(fs.readFileSync(path.join(ROOT, 'apps/desktop/package.json'))).version,
  };
  const result = { id: entry.id, checkedAt: new Date().toISOString(), ...versions, tags: entry.tags, stages: Object.fromEntries(STAGES.map((stage) => [stage, { status: 'unknown' }])) };
  const stage = async (name, action) => {
    try { const detail = await action(); result.stages[name] = { status: 'pass', ...detail }; return detail; }
    catch (error) { result.stages[name] = { status: 'fail', message: redacted(error.message) }; result.failedStage = name; throw error; }
  };
  const page = await context.newPage();
  let popup;
  try {
    const directSource = /\.m3u8(?:\?|$)|\.mp4(?:\?|$)/i.test(entry.url);
    const pageUrl = directSource ? `${fixture.baseUrl}/pages/external.html?url=${encodeURIComponent(entry.url)}` : entry.url;
    result.pageMode = directSource ? 'local-test-player' : 'source-page';
    await stage('S1', async () => {
      await page.goto(pageUrl, { waitUntil: 'domcontentloaded', timeout: 25_000 });
      for (const step of entry.steps || []) {
        const target = step.frame ? page.frameLocator(step.frame) : page;
        if (step.click) await target.locator(step.click).click();
        if (step.waitFor) await target.locator(step.waitFor).waitFor();
      }
    });
    const tabId = await worker.evaluate(async (url) => (await chrome.tabs.query({})).find((tab) => tab.url === url)?.id, page.url());
    if (!tabId) throw new Error('Browser tab could not be resolved');
    popup = await context.newPage();
    const extensionId = new URL(worker.url()).host;
    await popup.goto(`chrome-extension://${extensionId}/popup.html?tab=${tabId}`);
    let items = [];
    const detectionDeadline = Date.now() + 20_000;
    const readItems = async () => {
      const response = await popup.evaluate((id) => chrome.runtime.sendMessage({ cmd: 'GET_TAB_MEDIA', tabId: id }), tabId);
      items = response?.items || [];
    };
    await stage('S2', async () => {
      do {
        await readItems();
        if (items.length) return { count: items.length };
        await delay(250);
      } while (Date.now() < detectionDeadline);
      throw new Error('No video detected within 20 seconds');
    });
    await stage('S3', async () => {
      while (Number.isFinite(entry.expect?.rows) && items.length < entry.expect.rows && Date.now() < detectionDeadline) {
        await delay(250);
        await readItems();
      }
      // Never truncate extra rows to meet the expectation: over-counts are failures.
      if (Number.isFinite(entry.expect?.rows) && items.length !== entry.expect.rows) throw new Error(`Expected ${entry.expect.rows} rows; found ${items.length}`);
      return { count: items.length };
    });
    let item = items[0];
    if (entry.expect?.variants != null) await stage('S4', async () => {
      let variants = item.variants || item.hlsVariants?.variants || [];
      while (variants.length < entry.expect.variants && Date.now() < detectionDeadline) {
        await delay(250);
        await readItems();
        if (Number.isFinite(entry.expect?.rows) && items.length !== entry.expect.rows) throw new Error(`Row count changed while discovering variants: expected ${entry.expect.rows}; found ${items.length}`);
        item = items[0];
        variants = item.variants || item.hlsVariants?.variants || [];
      }
      if (variants.length !== entry.expect.variants) throw new Error(`Expected ${entry.expect.variants} variants; found ${variants.length}`);
      return { count: variants.length };
    });
    else result.stages.S4 = { status: 'na' };
    const mediaUrl = item.url || item.mediaUrl || entry.mediaUrl;
    const headers = item.headers || item.requestHeaders || {};
    await stage('S5', () => firstSegmentCheck(mediaUrl, headers));
    let download;
    await stage('S6', async () => {
      download = await downloadMedia({ url: mediaUrl, directory: outputDirectory, headers, mediaType: /\.mp4(?:\?|$)/i.test(mediaUrl) ? 'file' : 'hls', probe: { seconds: 30 }, verify: false });
    });
    await stage('S7', async () => {
      const metadata = await probeFile(download.filePath);
      if (!/mp4/.test(metadata.format) || !metadata.height) throw new Error('Result has no playable MP4 video stream');
      if (entry.expect?.minHeight && metadata.height < entry.expect.minHeight) throw new Error(`Video is ${metadata.height}p; expected at least ${entry.expect.minHeight}p`);
      if (!entry.tags?.includes('video-only') && !metadata.hasAudio) throw new Error('Expected audio stream is missing');
      return { height: metadata.height, hasAudio: metadata.hasAudio, durationSeconds: metadata.durationSeconds };
    });
    if (full) await stage('S8', async () => {
      const completed = await downloadMedia({ url: mediaUrl, directory: outputDirectory, headers, mediaType: /\.mp4(?:\?|$)/i.test(mediaUrl) ? 'file' : 'hls' });
      if (entry.expect?.durationSeconds && Math.abs(completed.metadata.durationSeconds - entry.expect.durationSeconds) > (entry.expect.tolerance || 5)) throw new Error('Full duration differs from expectation');
      return { durationSeconds: completed.metadata.durationSeconds };
    });
  } catch (error) {
    if (!result.failedStage) { result.failedStage = 'S1'; result.stages.S1 = { status: 'fail', message: redacted(error.message) }; }
  } finally { await popup?.close(); await page.close(); }
  return result;
}

async function main(argv = process.argv.slice(2)) {
  process.env.LOG_LEVEL = 'error';
  process.env.DISABLE_FILE_LOGS = '1';
  const flag = (name) => argv.includes(name);
  const value = (name) => argv[argv.indexOf(name) + 1];
  const allSeeds = seeds();
  const resultsDirectory = path.join(__dirname, 'results');
  fs.mkdirSync(resultsDirectory, { recursive: true });
  const prior = fs.readdirSync(resultsDirectory).filter((name) => name.endsWith('.json')).sort().flatMap((name) => JSON.parse(fs.readFileSync(path.join(resultsDirectory, name))).results || []);
  if (flag('--matrix-only')) {
    // Fixture ports are disposable. Recover only public identifiers and technique
    // tags from evidence, never stale source URLs, headers or browser state.
    const localEntries = [...new Map(prior
      .filter((result) => /^fixture-[a-z0-9-]+$/.test(result.id) && result.tags?.includes('local-fixture'))
      .map((result) => [result.id, { id: result.id, tags: result.tags }])).values()];
    fs.writeFileSync(path.join(__dirname, 'COMPATIBILITY.md'), buildMatrix([...allSeeds, ...localEntries], prior));
    return;
  }
  const fixture = await startFixtureServer();
  const localEntries = ['direct', 'hls', 'iframe', 'nested', 'click', 'base64', 'fetch', 'xhr', 'poster', 'og', 'none', 'variants', 'two', 'spa'].map((kind) => ({
    id: `fixture-${kind}`, url: `${fixture.baseUrl}/pages/${kind}.html`, permission: 'Generated test pattern owned by this project', tags: ['local-fixture', kind], steps: kind === 'click' ? [{ click: '#play' }] : [], expect: { rows: kind === 'two' ? 2 : 1, ...(kind === 'variants' ? { variants: 3 } : {}) },
  }));
  let entries = flag('--site') ? [...allSeeds, ...localEntries] : flag('--external') ? allSeeds : localEntries;
  if (flag('--site')) entries = entries.filter((entry) => entry.id === value('--site'));
  if (flag('--tag')) entries = entries.filter((entry) => entry.tags?.includes(value('--tag')));
  if (!entries.length) { await fixture.close(); throw new Error('No matching compatibility entries'); }
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'snagthis-compat-browser-'));
  const extensionPath = path.join(ROOT, 'apps/extension');
  let context;
  try {
    context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: !flag('--headed'), args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`, '--autoplay-policy=no-user-gesture-required'] });
    const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
    const results = [];
    for (const entry of entries) {
      const result = await runSite({ context, worker, fixture, entry, full: flag('--full'), outputDirectory: path.join(fixture.directory, 'compat-output') });
      results.push(result);
      console.log(`${entry.id}: ${result.failedStage ? `failed ${result.failedStage}` : 'passed through S7'}`);
    }
    const date = new Date().toISOString().replaceAll(':', '-');
    fs.writeFileSync(path.join(resultsDirectory, `${date}.json`), JSON.stringify({ checkedAt: new Date().toISOString(), results }, null, 2) + '\n');
    fs.writeFileSync(path.join(__dirname, 'COMPATIBILITY.md'), buildMatrix([...allSeeds, ...localEntries], [...prior, ...results]));
    // A changing public site is evidence, not a CI gate. Fixtures remain a hard gate.
    if (entries.every((entry) => entry.tags?.includes('local-fixture')) && results.some((result) => result.failedStage)) process.exitCode = 1;
  } finally { await context?.close(); await fixture.close(); fs.rmSync(profile, { recursive: true, force: true }); }
}

module.exports = { buildMatrix, redacted, runSite, main };
if (require.main === module) main().catch((error) => { console.error(redacted(error.message)); process.exitCode = 1; });
