// Generated by scripts/render-brand-assets.cjs. Do not edit by hand.
// The SnagThis lockup on its pixel grid: Jersey 15 capitals, then the Pixel bevel button.
export const SNAGTHIS_LOGO = {
  width: 120,
  height: 22,
  capTop: 3.5,
  capHeight: 15,
  cursorWidth: 10,
  colors: { snag: '#ffffff', orange: '#fa5d0e', deep: '#bd3f00', amber: '#ffb238', night: '#0c0e11' },
  letters: [
    { char: 'S', pen: -1, left: 0, right: 11, d: 'M2 3.5h7v1h-7zM1 4.5h9v1h-9zM0 5.5h11v1h-11zM0 6.5h4v1h-4zM7 6.5h4v1h-4zM0 7.5h3v1h-3zM8 7.5h3v1h-3zM0 8.5h4v1h-4zM0 9.5h9v1h-9zM1 10.5h9v1h-9zM2 11.5h9v1h-9zM7 12.5h4v1h-4zM0 13.5h3v1h-3zM8 13.5h3v1h-3zM0 14.5h4v1h-4zM7 14.5h4v1h-4zM0 15.5h11v1h-11zM1 16.5h9v1h-9zM2 17.5h7v1h-7z' },
    { char: 'N', pen: 13, left: 14, right: 25, d: 'M14 3.5h4v1h-4zM22 3.5h3v1h-3zM14 4.5h4v1h-4zM22 4.5h3v1h-3zM14 5.5h5v1h-5zM22 5.5h3v1h-3zM14 6.5h5v1h-5zM22 6.5h3v1h-3zM14 7.5h6v1h-6zM22 7.5h3v1h-3zM14 8.5h6v1h-6zM22 8.5h3v1h-3zM14 9.5h7v1h-7zM22 9.5h3v1h-3zM14 10.5h3v1h-3zM18 10.5h3v1h-3zM22 10.5h3v1h-3zM14 11.5h3v1h-3zM18 11.5h7v1h-7zM14 12.5h3v1h-3zM19 12.5h6v1h-6zM14 13.5h3v1h-3zM19 13.5h6v1h-6zM14 14.5h3v1h-3zM20 14.5h5v1h-5zM14 15.5h3v1h-3zM20 15.5h5v1h-5zM14 16.5h3v1h-3zM21 16.5h4v1h-4zM14 17.5h3v1h-3zM21 17.5h4v1h-4z' },
    { char: 'A', pen: 27, left: 28, right: 38, d: 'M32 3.5h2v1h-2zM31 4.5h4v1h-4zM30 5.5h6v1h-6zM29 6.5h8v1h-8zM28 7.5h4v1h-4zM34 7.5h4v1h-4zM28 8.5h3v1h-3zM35 8.5h3v1h-3zM28 9.5h3v1h-3zM35 9.5h3v1h-3zM28 10.5h3v1h-3zM35 10.5h3v1h-3zM28 11.5h10v1h-10zM28 12.5h10v1h-10zM28 13.5h10v1h-10zM28 14.5h3v1h-3zM35 14.5h3v1h-3zM28 15.5h3v1h-3zM35 15.5h3v1h-3zM28 16.5h3v1h-3zM35 16.5h3v1h-3zM28 17.5h3v1h-3zM35 17.5h3v1h-3z' },
    { char: 'G', pen: 40, left: 41, right: 51, d: 'M43 3.5h6v1h-6zM42 4.5h8v1h-8zM41 5.5h10v1h-10zM41 6.5h4v1h-4zM48 6.5h3v1h-3zM41 7.5h3v1h-3zM41 8.5h3v1h-3zM41 9.5h3v1h-3zM46 9.5h5v1h-5zM41 10.5h3v1h-3zM46 10.5h5v1h-5zM41 11.5h3v1h-3zM46 11.5h5v1h-5zM41 12.5h3v1h-3zM48 12.5h3v1h-3zM41 13.5h3v1h-3zM48 13.5h3v1h-3zM41 14.5h4v1h-4zM47 14.5h4v1h-4zM41 15.5h10v1h-10zM42 16.5h8v1h-8zM43 17.5h6v1h-6z' },
    { char: 'T', pen: 53, left: 54, right: 63, d: 'M54 3.5h9v1h-9zM54 4.5h9v1h-9zM54 5.5h9v1h-9zM57 6.5h3v1h-3zM57 7.5h3v1h-3zM57 8.5h3v1h-3zM57 9.5h3v1h-3zM57 10.5h3v1h-3zM57 11.5h3v1h-3zM57 12.5h3v1h-3zM57 13.5h3v1h-3zM57 14.5h3v1h-3zM57 15.5h3v1h-3zM57 16.5h3v1h-3zM57 17.5h3v1h-3z' },
    { char: 'H', pen: 65, left: 66, right: 76, d: 'M66 3.5h3v1h-3zM73 3.5h3v1h-3zM66 4.5h3v1h-3zM73 4.5h3v1h-3zM66 5.5h3v1h-3zM73 5.5h3v1h-3zM66 6.5h3v1h-3zM73 6.5h3v1h-3zM66 7.5h3v1h-3zM73 7.5h3v1h-3zM66 8.5h3v1h-3zM73 8.5h3v1h-3zM66 9.5h10v1h-10zM66 10.5h10v1h-10zM66 11.5h10v1h-10zM66 12.5h3v1h-3zM73 12.5h3v1h-3zM66 13.5h3v1h-3zM73 13.5h3v1h-3zM66 14.5h3v1h-3zM73 14.5h3v1h-3zM66 15.5h3v1h-3zM73 15.5h3v1h-3zM66 16.5h3v1h-3zM73 16.5h3v1h-3zM66 17.5h3v1h-3zM73 17.5h3v1h-3z' },
    { char: 'I', pen: 78, left: 79, right: 82, d: 'M79 3.5h3v1h-3zM79 4.5h3v1h-3zM79 5.5h3v1h-3zM79 6.5h3v1h-3zM79 7.5h3v1h-3zM79 8.5h3v1h-3zM79 9.5h3v1h-3zM79 10.5h3v1h-3zM79 11.5h3v1h-3zM79 12.5h3v1h-3zM79 13.5h3v1h-3zM79 14.5h3v1h-3zM79 15.5h3v1h-3zM79 16.5h3v1h-3zM79 17.5h3v1h-3z' },
    { char: 'S', pen: 84, left: 85, right: 96, d: 'M87 3.5h7v1h-7zM86 4.5h9v1h-9zM85 5.5h11v1h-11zM85 6.5h4v1h-4zM92 6.5h4v1h-4zM85 7.5h3v1h-3zM93 7.5h3v1h-3zM85 8.5h4v1h-4zM85 9.5h9v1h-9zM86 10.5h9v1h-9zM87 11.5h9v1h-9zM92 12.5h4v1h-4zM85 13.5h3v1h-3zM93 13.5h3v1h-3zM85 14.5h4v1h-4zM92 14.5h4v1h-4zM85 15.5h11v1h-11zM86 16.5h9v1h-9zM87 17.5h7v1h-7z' },
  ],
  button: {
    x: 104,
    y: 3,
    size: 16,
    tile: 'M3 0h10v1h-10zM1 1h14v1h-14zM1 2h14v1h-14zM0 3h16v1h-16zM0 4h16v1h-16zM0 5h16v1h-16zM0 6h16v1h-16zM0 7h16v1h-16zM0 8h16v1h-16zM0 9h16v1h-16zM0 10h16v1h-16zM0 11h16v1h-16zM0 12h16v1h-16zM1 13h14v1h-14zM1 14h14v1h-14zM3 15h10v1h-10z',
    hi: 'M3 0h10v1h-10zM1 1h2v1h-2zM13 1h1v1h-1zM1 2h1v1h-1zM0 3h1v1h-1zM0 4h1v1h-1zM0 5h1v1h-1zM0 6h1v1h-1zM0 7h1v1h-1zM0 8h1v1h-1zM0 9h1v1h-1zM0 10h1v1h-1zM0 11h1v1h-1zM0 12h1v1h-1zM1 13h1v1h-1z',
    lo: 'M14 1h1v1h-1zM14 2h1v1h-1zM15 3h1v1h-1zM15 4h1v1h-1zM15 5h1v1h-1zM15 6h1v1h-1zM15 7h1v1h-1zM15 8h1v1h-1zM15 9h1v1h-1zM15 10h1v1h-1zM15 11h1v1h-1zM15 12h1v1h-1zM14 13h1v1h-1zM1 14h2v1h-2zM13 14h2v1h-2zM3 15h10v1h-10z',
    shadow: 'M13 8h1v1h-1zM11 9h3v1h-3zM10 10h2v1h-2zM8 11h3v1h-3zM7 12h2v1h-2zM6 13h2v1h-2z',
    glyph: 'M5 3h2v1h-2zM5 4h3v1h-3zM5 5h5v1h-5zM5 6h6v1h-6zM5 7h8v1h-8zM5 8h8v1h-8zM5 9h6v1h-6zM5 10h5v1h-5zM5 11h3v1h-3zM5 12h2v1h-2z',
  },
} as const;
